import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import RootLayoutProviders from "./_components/layout/providers";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

/**
 * @param {import("react").PropsWithChildren} props
 */
export default function RootLayout(props) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <RootLayoutProviders>{props.children}</RootLayoutProviders>
      </body>
    </html>
  );
}
